### ISSUE TITLE
务必查看

### ISSUE THREAD

**Issue by ACGtutusang** [spikensbror-dotnet/nsonic#14]
你白纸革命，你放你自己网站不行吗，为什么连syzx都放上去；
你知道不知道，你这种行为，那些不知道具体经过的人都在议论我，是我在给你背锅；
你知道不知道你连声招呼都不打，就消失，你有想过我吗？你有想过网站进不去我该怎么办吗？
你知不知道，我白天上一天的班，晚上还要操心网站吗，你知道我压力有多大吗？
我甚至都不知道该怎么在我群里给群友说发生了什么；
你知不知道我和irol有多担心你；
所以，咱就给个确切的消息，到底什么时候回来？
你要是还想回来，但不想跟tg那群人键政，那咱就zul里交流，不用理会他们。
就这样吧，我想你看到了这条iss也会删除吧；
总之，请一定要给个确切的消息，这样完全没有音信，我实在无力接受。
或者你想清净一阵子，可以，那请把syzx解开，咱有事就github交流，一般没有致命BUG我不会骚扰你，pls

**Comment by ACGtutusang** [comment]
@n0099

**Comment by spikensbror** [comment]
No idea what this is about, please write an issue in English if you are experiencing any problems.
